name: spendly
description: Spendly - Build Better Money Habits, Daily for Filipino youth.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  supabase_flutter: ^2.5.0
  flutter_riverpod: ^2.5.1
  radix_icons: ^1.0.1
  intl: ^0.19.0
  shared_preferences: ^2.3.0
  uuid: ^4.4.0
  http: ^1.6.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

